[package]
name = "game-3d-toolkit"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.11"
model-batch-processor = { path = "../model-batch-processor" }
argparse-gd = { path = "../argparse-gd" }

[build-dependencies]
askama = "0.11.1"
regex = "1.7.0"
