name: Release Packaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: 3.5.1

jobs:
  release:
    name: Release Packaging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: if [[ $(docker inspect --type=image godot | wc -l) -eq 1 ]]; then docker build --file Dockerfile --build-arg GODOT_VERSION=${{ env.GODOT_VERSION }} --tag godot:${{ env.GODOT_VERSION }} .; fi
      - name: Run export
        run: docker run --volume $PWD:/srv --workdir /srv godot:${{ env.GODOT_VERSION }} cargo make --no-workspace --env BUILD_TARGET=${{ matrix.target }} -- export
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: slippery-${{ matrix.target }}
          path: bin/${{ matrix.target }}/
